stages:
  - build
  - push

variables:
  GITHUB_REPO: "https://github.com/username/repo.git"  # Replace with your repo URL
  DOCKER_IMAGE: "my-docker-registry.com/namespace/image:tag"

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    # Clone the GitHub repository
    - ls -la
    - docker build -t microservice-a:1.0 -f microservice-a/Dockerfile  . # Run only on main branch

